# Generated by Django 6.0 on 2025-12-17 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowSubcommunities', models.BooleanField()),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('logoUrl', models.CharField(max_length=255)),
                ('rulesMarkdown', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communitys',
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Money',
                'verbose_name_plural': 'Moneys',
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicKey', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('secretRef', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PaymentProvider',
                'verbose_name_plural': 'PaymentProviders',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='CustomCoreAPI.community')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Reserved', 'Reserved'), ('Completed', 'Completed'), ('Draft', 'Draft')], max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('expiresAt', models.DateTimeField()),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('New', 'New'), ('LikeNew', 'LikeNew'), ('Poor', 'Poor'), ('Fair', 'Fair')], max_length=255)),
                ('mediaUrls', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('Service', 'Service'), ('Product', 'Product')], max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('exchangeModes', models.CharField(choices=[('Price', 'Price'), ('Exchange', 'Exchange'), ('Donation', 'Donation')], max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('uid', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='CustomCoreAPI.category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemVariant', to='CustomCoreAPI.item')),
            ],
            options={
                'verbose_name': 'ItemVariant',
                'verbose_name_plural': 'ItemVariants',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('uid', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Location', to='CustomCoreAPI.community')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='CustomCoreAPI.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='Money',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='CustomCoreAPI.money'),
        ),
        migrations.AddField(
            model_name='community',
            name='PaymentProvider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Community', to='CustomCoreAPI.paymentprovider'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
                ('isAdmin', models.BooleanField()),
                ('fullName', models.CharField(max_length=255)),
                ('isModerator', models.BooleanField()),
                ('email', models.CharField(max_length=255)),
                ('avgRating', models.FloatField()),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], max_length=255)),
                ('ratingCount', models.IntegerField()),
                ('avatarUrl', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User', to='CustomCoreAPI.community')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('Locker', 'Locker'), ('InPerson', 'InPerson'), ('Mail', 'Mail')], max_length=255)),
                ('receiptUrl', models.CharField(max_length=255)),
                ('paymentMethod', models.CharField(choices=[('NoPayment', 'NoPayment'), ('Multibanco', 'Multibanco'), ('MBWay', 'MBWay'), ('PayPal', 'PayPal')], max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=255)),
                ('closedAt', models.DateTimeField()),
                ('mode', models.CharField(choices=[('Donation', 'Donation'), ('Sale', 'Sale'), ('Exchange', 'Exchange')], max_length=255)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transaction', to='CustomCoreAPI.item')),
                ('Money', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Transaction', to='CustomCoreAPI.money')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transaction', to='CustomCoreAPI.user')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservedUntil', models.DateTimeField()),
                ('reservedFrom', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Released', 'Released'), ('Expired', 'Expired')], max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Reservation', to='CustomCoreAPI.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Reservation', to='CustomCoreAPI.user')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Offensive', 'Offensive'), ('Safety', 'Safety'), ('Other', 'Other'), ('Spam', 'Spam'), ('Fraud', 'Fraud')], max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('status', models.CharField(choices=[('UnderReview', 'UnderReview'), ('Resolved', 'Resolved'), ('Ignored', 'Ignored'), ('Open', 'Open')], max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Report', to='CustomCoreAPI.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Report', to='CustomCoreAPI.user')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('stars', models.IntegerField()),
                ('uid', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Rating', to='CustomCoreAPI.user')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Request', 'Request'), ('PriceOffer', 'PriceOffer'), ('ExchangeOffer', 'ExchangeOffer')], max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Expired', 'Expired'), ('Pending', 'Pending')], max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Offer', to='CustomCoreAPI.item')),
                ('Money', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Offer', to='CustomCoreAPI.money')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Offer', to='CustomCoreAPI.user')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='CustomCoreAPI.user'),
        ),
    ]
