# Generated by Django 6.0 on 2025-12-17 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('logoUrl', models.CharField(max_length=255)),
                ('rulesMarkdown', models.CharField(max_length=255)),
                ('allowSubcommunities', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communitys',
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Money',
                'verbose_name_plural': 'Moneys',
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('publicKey', models.CharField(max_length=255)),
                ('secretRef', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PaymentProvider',
                'verbose_name_plural': 'PaymentProviders',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='CoreAPI.community')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('mediaUrls', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Reserved', 'Reserved'), ('Completed', 'Completed'), ('Archived', 'Archived')], max_length=255)),
                ('condition', models.CharField(choices=[('Poor', 'Poor'), ('New', 'New'), ('LikeNew', 'LikeNew'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=255)),
                ('kind', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], max_length=255)),
                ('exchangeModes', models.CharField(choices=[('Donation', 'Donation'), ('Exchange', 'Exchange'), ('Price', 'Price')], max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('expiresAt', models.DateTimeField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='CoreAPI.category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Conversation', to='CoreAPI.item')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemVariant', to='CoreAPI.item')),
            ],
            options={
                'verbose_name': 'ItemVariant',
                'verbose_name_plural': 'ItemVariants',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Location', to='CoreAPI.community')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='CoreAPI.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='Money',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='CoreAPI.money'),
        ),
        migrations.AddField(
            model_name='community',
            name='PaymentProvider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Community', to='CoreAPI.paymentprovider'),
        ),
        migrations.CreateModel(
            name='SubCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SubCommunity', to='CoreAPI.community')),
            ],
            options={
                'verbose_name': 'SubCommunity',
                'verbose_name_plural': 'SubCommunitys',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='SubCommunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='CoreAPI.subcommunity'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('avatarUrl', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('isAdmin', models.BooleanField()),
                ('isModerator', models.BooleanField()),
                ('avgRating', models.FloatField()),
                ('ratingCount', models.IntegerField()),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User', to='CoreAPI.community')),
                ('Conversation', models.ManyToManyField(blank=True, related_name='User', to='CoreAPI.conversation')),
                ('SubCommunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User', to='CoreAPI.subcommunity')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('closedAt', models.DateTimeField()),
                ('mode', models.CharField(choices=[('Donation', 'Donation'), ('Sale', 'Sale'), ('Exchange', 'Exchange')], max_length=255)),
                ('delivery', models.CharField(choices=[('Locker', 'Locker'), ('Mail', 'Mail'), ('InPerson', 'InPerson')], max_length=255)),
                ('receiptUrl', models.CharField(max_length=255)),
                ('paymentMethod', models.CharField(choices=[('MBWay', 'MBWay'), ('PayPal', 'PayPal'), ('NoPayment', 'NoPayment'), ('Multibanco', 'Multibanco')], max_length=255)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=255)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transaction', to='CoreAPI.item')),
                ('Money', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Transaction', to='CoreAPI.money')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transaction', to='CoreAPI.user')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservedFrom', models.DateTimeField()),
                ('reservedUntil', models.DateTimeField()),
                ('uid', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('Active', 'Active'), ('Expired', 'Expired')], max_length=255)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Reservation', to='CoreAPI.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Reservation', to='CoreAPI.user')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('Fraud', 'Fraud'), ('Safety', 'Safety'), ('Offensive', 'Offensive'), ('Spam', 'Spam'), ('Other', 'Other')], max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Ignored', 'Ignored'), ('Resolved', 'Resolved'), ('UnderReview', 'UnderReview')], max_length=255)),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Report', to='CoreAPI.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Report', to='CoreAPI.user')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('stars', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Rating', to='CoreAPI.user')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Request', 'Request'), ('ExchangeOffer', 'ExchangeOffer'), ('PriceOffer', 'PriceOffer')], max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('status', models.CharField(choices=[('Withdrawn', 'Withdrawn'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=255)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Offer', to='CoreAPI.item')),
                ('Money', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Offer', to='CoreAPI.money')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Offer', to='CoreAPI.user')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('sentAt', models.DateTimeField()),
                ('kind', models.CharField(choices=[('System', 'System'), ('Text', 'Text'), ('Image', 'Image')], max_length=255)),
                ('attachments', models.CharField(max_length=255)),
                ('Conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Message', to='CoreAPI.conversation')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Message', to='CoreAPI.user')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='CoreAPI.user'),
        ),
    ]
