/**
 * appName - Main Application Entry Point
 * Generated by BESSER Framework
 */

import { Router } from './router.js';
import { ComponentRegistry } from './components.js';

class App {
    constructor() {
        this.router = null;
        this.components = null;
        this.state = {
            user: null,
            loading: false
        };
    }
    
    /**
     * Initialize the application
     */
    async init() {
        console.log('Initializing appName...');
        
        // Initialize component registry
        this.components = new ComponentRegistry();
        
        // Initialize router
        this.router = new Router();
        
        // Setup event listeners
        this.setupEventListeners();
        
        // Start router
        this.router.init();
        
        console.log('appName initialized successfully');
    }
    
    /**
     * Setup global event listeners
     */
    setupEventListeners() {
        // Mobile menu toggle
        const navbarToggle = document.getElementById('navbar-toggle');
        const navbarMenu = document.getElementById('navbar-menu');
        
        if (navbarToggle && navbarMenu) {
            navbarToggle.addEventListener('click', () => {
                navbarToggle.classList.toggle('active');
                navbarMenu.classList.toggle('active');
            });
            
            // Close menu when clicking a link
            navbarMenu.querySelectorAll('.navbar-link').forEach(link => {
                link.addEventListener('click', () => {
                    navbarToggle.classList.remove('active');
                    navbarMenu.classList.remove('active');
                });
            });
        }
        
        // Handle navigation clicks
        document.addEventListener('click', (e) => {
            const link = e.target.closest('a[href^="#"]');
            if (link) {
                e.preventDefault();
                const path = link.getAttribute('href').substring(1);
                this.router.navigate(path);
            }
        });
        
        // Update active nav link on route change
        window.addEventListener('popstate', () => {
            this.updateActiveNavLink();
        });
    }
    
    /**
     * Update active navigation link based on current route
     */
    updateActiveNavLink() {
        const currentPath = window.location.hash.substring(1) || '/';
        document.querySelectorAll('.navbar-link').forEach(link => {
            const linkPath = link.getAttribute('data-route');
            if (linkPath === currentPath) {
                link.classList.add('active');
            } else {
                link.classList.remove('active');
            }
        });
    }
    
    /**
     * Show loading state
     */
    showLoading() {
        this.state.loading = true;
        const mainContent = document.getElementById('main-content');
        if (mainContent) {
            mainContent.innerHTML = `
                <div class="loading">
                    <div class="spinner"></div>
                    <p>Loading...</p>
                </div>
            `;
        }
    }
    
    /**
     * Hide loading state
     */
    hideLoading() {
        this.state.loading = false;
    }
    
    /**
     * Show error message
     */
    showError(message) {
        const mainContent = document.getElementById('main-content');
        if (mainContent) {
            mainContent.innerHTML = `
                <div class="error">
                    <h3>Error</h3>
                    <p>${message}</p>
                </div>
            `;
        }
    }
}

// Initialize app when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => {
        const app = new App();
        app.init();
        window.app = app; // Make app globally accessible
    });
} else {
    const app = new App();
    app.init();
    window.app = app;
}

export default App;