<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="gui"
    nsURI="http://community/localSwap/gui"
    nsPrefix="gui">

  <!-- ===================== -->
  <!--      ENUMERATIONS     -->
  <!-- ===================== -->

  <eClassifiers xsi:type="ecore:EEnum" name="ButtonType">
    <eLiterals name="RaisedButton" value="0"/>
    <eLiterals name="TextButton" value="1"/>
    <eLiterals name="IconButton" value="2"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="ButtonActionType">
    <eLiterals name="OpenForm" value="0"/>
    <eLiterals name="Navigate" value="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="InputFieldType">
    <eLiterals name="Text" value="0"/>
    <eLiterals name="Number" value="1"/>
    <eLiterals name="Date" value="2"/>
    <eLiterals name="Search" value="3"/>
    <eLiterals name="Email" value="4"/>
    <eLiterals name="Password" value="5"/>
  </eClassifiers>

  <!-- ===================== -->
  <!--   COMPONENTS    -->
  <!-- ===================== -->

  <eClassifiers xsi:type="ecore:EClass" name="ViewElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ViewComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="DataSourceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSourceClassName"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fields"
                         upperBound="-1"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- ===================== -->
  <!--   VIEW ELEMENT TYPES -->
  <!-- ===================== -->

  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//ViewElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buttonType"
                         eType="#//ButtonType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionType"
                         eType="#//ButtonActionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetScreen"
                         eType="#//Screen" lowerBound="0" upperBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="InputField" eSuperTypes="#//ViewElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"
                         eType="#//InputFieldType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationRules"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="DataList" eSuperTypes="#//ViewElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listSources"
                         upperBound="-1" eType="#//DataSourceElement"/>
  </eClassifiers>

  <!-- ===================== -->
  <!--         SCREEN        -->
  <!-- ===================== -->

  <eClassifiers xsi:type="ecore:EClass" name="Screen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x_dpi"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y_dpi"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="screenSize"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMainPage"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewElements"
                         upperBound="-1" containment="true" eType="#//ViewElement"/>
  </eClassifiers>

  <!-- ===================== -->
  <!--        MODULE         -->
  <!-- ===================== -->

  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screens"
                         upperBound="-1" containment="true" eType="#//Screen"/>
  </eClassifiers>

  <!-- ===================== -->
  <!--        GUI MODEL      -->
  <!-- ===================== -->

  <eClassifiers xsi:type="ecore:EClass" name="GUIModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionCode"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionName"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="screenCompatibility"
                         eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules"
                         upperBound="-1" containment="true" eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewComponent"
                         lowerBound="0" upperBound="1" containment="true" eType="#//ViewComponent"/>
  </eClassifiers>

</ecore:EPackage>
